### ISSUE TITLE
Problems in attaching a picture to the dish

### ISSUE THREAD

**Issue by andreumarti** [eat-this-one/eat-this-one#5]
Using lollipop on Nexus 5.

Unable to add a picture to a dish, not only from the gallery but also from the camera.

I have just tested with the above OS and phone. I do not know whether the problem occurs with other devices and OSs.

Cheers

**Comment by dmonllao** [comment]
Hi mr Marti, thanks for reporting the issue.

Strange, I am also the proud owner of a Nexus 5 and I can attach pictures without any problem (gallery and camera all as expected) A couple of workmates have the same device and they didn't have problems either.

I will check the server logs, I'm sending an error report to the server if there is any problem related with the camera on any client device (https://github.com/eat-this-one/eat-this-one/blob/master/public/javascripts/directives/photo.js#L26) I will check it later.

Many thanks for the report

**Comment by andreumarti** [comment]
Sorry David, I restarted the device and everything worked as expected.
